const {test}=require('node:test'),assert=require('node:assert/strict'),G=require('../game');
function staged(pieces,steps=[1],turn=0){const g=G.newGame(['a','b']);Object.assign(g,{pieces,turn,phase:'move',credits:0,pending:steps.map((steps,i)=>({id:i+1,steps,label:['','도','개','걸','윷','모'][steps]}))});return g;}
test('2~64명 중복·누락 없는 대진과 첫 라운드만 부전승',()=>{for(let n=2;n<=64;n++){const ids=Array.from({length:n},(_,i)=>String(i)),r=G.bracket(ids);assert.deepEqual(r[0].flatMap(m=>m.players).filter(x=>x!==null).sort(),ids.sort());let size=2;while(size<n)size*=2;assert.equal(r[0].filter(m=>m.status==='bye').length,size-n);assert.equal(r.at(-1).length,1);}});
test('19명·20명 실제 경기와 부전승 분산',()=>{for(const[n,byes,count]of[[19,13,3],[20,12,4]]){const r=G.bracket(Array.from({length:n},(_,i)=>i));assert.equal(r[0].filter(m=>m.status==='bye').length,byes);assert.equal(r[0].filter(m=>m.status==='pending').length,count);}const r=G.bracket(Array.from({length:20},(_,i)=>i));for(let i=0;i<16;i+=4)assert.equal(r[0].slice(i,i+4).filter(m=>m.status==='pending').length,1);});
test('바깥길·대각선 경유·중앙에서 선택·완주',()=>{assert.equal(G.destination('start',5),5);assert.equal(G.destination(5,3),'ca');assert.equal(G.destination(5,5),'a5');assert.equal(G.destination(4,2),6);assert.equal(G.destination(5,1,false),6);assert.equal(G.destination(10,3),'cb');assert.equal(G.destination('ca',1),'b4');assert.equal(G.destination('ca',1,false),'a4');assert.equal(G.destination('a2',2),'a4');assert.equal(G.destination('b2',2),'b4');assert.equal(G.destination(19,1),20);assert.equal(G.destination(20,1),'home');});
test('4개 윷의 16가지 결과',()=>{const counts={};for(let bits=0;bits<16;bits++){const g=G.newGame(['a','b']);let i=0;G.roll(g,()=>bits>>i++&1);counts[g.last.steps]=(counts[g.last.steps]||0)+1;}assert.deepEqual(counts,{1:4,2:6,3:4,4:1,5:1});});
test('모→도 누적, 1칸/5칸 도착 선택 및 순서 교환',()=>{for(const first of[1,2]){const g=G.newGame(['a','b']);g.turn=0;G.roll(g,()=>0);assert.equal(g.phase,'throw');assert.equal(g.pending[0].steps,5);let i=0;G.roll(g,()=>Number(i++===0));assert.equal(g.phase,'move');assert.deepEqual(g.pending.map(r=>r.steps),[5,1]);assert.deepEqual(G.options(g).filter(o=>o.piece===0).map(o=>o.dest),[5,1]);G.move(g,0,first,true);assert.equal(g.phase,'move');assert.equal(g.turn,0);G.move(g,1,first===1?2:1,true);assert.equal(g.turn,1);assert.equal(g.phase,'throw');}});
test('잡기·업기·중앙 충돌, 잡기 추가 던지기는 남은 결과 소진 뒤',()=>{const g=staged([[1,1],[3,3]],[2,1]);G.move(g,0,1,true);assert.deepEqual(g.pieces,[[3,3],['start','start']]);assert.equal(g.credits,1);assert.equal(g.phase,'move');G.move(g,0,2,true);assert.equal(g.phase,'throw');assert.equal(g.turn,0);const h=staged([['a2','start'],['cb','start']]);G.move(h,0,1,true);assert.equal(h.pieces[1][0],'start');const k=staged([['ca','cb'],['start','start']]);G.move(k,0,1,false);assert.deepEqual(k.pieces[0],['a4','a4']);});
test('대기 말 개별 출발·불법 결과·완주 말 이동 거절',()=>{const g=staged([['start','start'],['start','start']]);assert.throws(()=>G.move(g,0,99,true));assert.throws(()=>G.move(g,9,1,true));G.move(g,0,1,true);assert.deepEqual(g.pieces[0],[1,'start']);const h=staged([[20,'home'],['start','start']]);assert.throws(()=>G.move(h,1,1,true));G.move(h,0,1,true);assert.equal(h.winner,'a');assert.throws(()=>G.roll(h));});
test('100개 자동 경기 두 말 완주로 종료',()=>{for(let n=0;n<100;n++){const g=G.newGame(['a','b']);let steps=0;while(g.winner===null&&steps++<2000)G.auto(g);assert.ok(g.winner);assert.ok(g.pieces[g.players.indexOf(g.winner)].every(p=>p==='home'));}});
